### PR TITLE
Cross compile to 2.12

### PR DESCRIPTION
**Pull request by lustefaniak**
Fixes https://github.com/MonsantoCo/kamon-prometheus/issues/11

This is ready for `library` project.

For 2.11 it contains Spray and Akka-HTTP endpoint, for 2.12 only Akka-HTTP.

I'm not sure what should be done about `demo` project. I think best approach would be to move that project into separate repository. If that is not an option, similar approach as in `library` could be used and demo could be ported to akka-http.

There are still some deprecations about using JavaConversions in ProtoBufFormat, but changing it makes code a little bit less readable. I think it should be done using `JavaConverters` and `breakOut` to reduce allocations, but can happen in next PR.

### CODE REVIEW

**Comment by lustefaniak** [comment]
sbt-doge skips `demo` from 2.12.2 build, all should be fine now.

**Comment by lustefaniak** [comment]
Hey @sattvik, do you think there is chance to get that merged and released? We are using 2.12 build in our applications for 2 months already and all is working fine. It would simplify our life if that was released upstream as now we are including copy of this codebase as module in sbt.

**Review by ElfoLiNk — APPROVED** [review]

**Comment by bzumhagen** [comment]
Any chance we can get this merged now? Looks like it's approved?

@lustefaniak, @ElfoLiNk

**Comment by lukasz-golebiewski** [comment]
@ElfoLiNk What is preventing this PR from being merged?

**Comment by lustefaniak** [comment]
Kamon 1.0 has now Prometheus support, so probably there is no point maintaining this.

**Pull request closed without merging**
